CREATE TABLE IF NOT EXISTS vuln_vulnerabilities (
    v_id INT AUTO_INCREMENT NOT NULL,
    e_id INT NOT NULL,
    created_on DATE DEFAULT DATE(CURRENT_TIMESTAMP),
    first_found DATETIME,
    indexed DATETIME,
    last_fixed DATETIME,
    last_found DATETIME,
    port_port INT,
    port_protocol VARCHAR(8),
    port_service VARCHAR(32),
    recast_reason VARCHAR(64),
    recast_rule_uuid VARCHAR(64),
    scan_schedule_uuid VARCHAR(64),
    scan_started_at DATETIME,
    scan_uuid VARCHAR(64),
    severity VARCHAR(16),
    severity_default_id INT,
    severity_id INT,
    severity_modification_type VARCHAR(16),
    source VARCHAR(8),
    state VARCHAR(16),
    PRIMARY KEY (v_id)
);