__MOCK_ALLPATCHES_RESPONSES = [
    {
        "message_type": "allpatches",
        "message_response": {
            "total": 25,
            "allpatches": [
                {
                    "updated_time": "1707917889000",
                    "installed": "55",
                    "patch_status_label": "--",
                    "bulletin_id": "MSWU\\\\-9328",
                    "patch_noreboot": "1",
                    "update_name": "Divalproex Sodium",
                    "platform": "1",
                    "platform_name": "Windows",
                    "missing": "6",
                    "download_status": "--",
                    "first_name": "Gazelle, thomson's",
                    "severity": "0",
                    "patch_id": "389369",
                    "patch_name": "In.mp3",
                    "patch_description": "Optional",
                    "patch_status_image": "--",
                    "vendor_name": "Kazio",
                    "failed": "2",
                    "status_label": "--",
                    "patch_released_time": "1703195936000",
                    "patch_size": "277304",
                },
                {
                    "updated_time": "1697663182000",
                    "installed": "2",
                    "patch_status_label": "--",
                    "bulletin_id": "MSWU\\\\-7121",
                    "patch_noreboot": "0",
                    "update_name": "Propranolol Hydrochloride",
                    "platform": "1",
                    "platform_name": "Windows",
                    "missing": "695",
                    "download_status": "--",
                    "first_name": "Reedbuck, bohor",
                    "severity": "2",
                    "patch_id": "065172",
                    "patch_name": "ConsequatUtNulla.jpeg",
                    "patch_description": "model",
                    "patch_status_image": "--",
                    "vendor_name": "Rhyloo",
                    "failed": "8",
                    "status_label": "--",
                    "patch_released_time": "1707478515000",
                    "patch_size": "843632212",
                },
                {
                    "updated_time": "1702115830000",
                    "installed": "24",
                    "patch_status_label": "--",
                    "bulletin_id": "MSWU\\\\-6643",
                    "patch_noreboot": "0",
                    "update_name": "MEGESTROL ACETATE",
                    "platform": "1",
                    "platform_name": "Windows",
                    "missing": "019",
                    "download_status": "--",
                    "first_name": "Burmese black mountain tortoise",
                    "severity": "2",
                    "patch_id": "191943",
                    "patch_name": "VestibulumAnteIpsum.mp3",
                    "patch_description": "Seamless",
                    "patch_status_image": "--",
                    "vendor_name": "Reallinks",
                    "failed": "2",
                    "status_label": "--",
                    "patch_released_time": "1711536307000",
                    "patch_size": "5696",
                },
                {
                    "updated_time": "1722114653000",
                    "installed": "974",
                    "patch_status_label": "--",
                    "bulletin_id": "MSWU\\\\-2296",
                    "patch_noreboot": "0",
                    "update_name": "Black Olive",
                    "platform": "1",
                    "platform_name": "Windows",
                    "missing": "544",
                    "download_status": "--",
                    "first_name": "Black kite",
                    "severity": "2",
                    "patch_id": "755690",
                    "patch_name": "Vivamus.mp3",
                    "patch_description": "Synergistic",
                    "patch_status_image": "--",
                    "vendor_name": "Mita",
                    "failed": "3",
                    "status_label": "--",
                    "patch_released_time": "1725187997000",
                    "patch_size": "358981988",
                },
                {
                    "updated_time": "1703338680000",
                    "installed": "151",
                    "patch_status_label": "--",
                    "bulletin_id": "MSWU\\\\-2057",
                    "patch_noreboot": "0",
                    "update_name": "ticarcillin disodium and clavulanate potassium",
                    "platform": "1",
                    "platform_name": "Windows",
                    "missing": "4",
                    "download_status": "--",
                    "first_name": "Stork, saddle-billed",
                    "severity": "3",
                    "patch_id": "900507",
                    "patch_name": "UtMassa.ppt",
                    "patch_description": "Seamless",
                    "patch_status_image": "--",
                    "vendor_name": "Twinte",
                    "failed": "6",
                    "status_label": "--",
                    "patch_released_time": "1721343130000",
                    "patch_size": "39584509",
                },
                {
                    "updated_time": "1703125844000",
                    "installed": "54",
                    "patch_status_label": "--",
                    "bulletin_id": "MSWU\\\\-3467",
                    "patch_noreboot": "1",
                    "update_name": "Saline",
                    "platform": "1",
                    "platform_name": "Windows",
                    "missing": "040",
                    "download_status": "--",
                    "first_name": "Deer, mule",
                    "severity": "1",
                    "patch_id": "723122",
                    "patch_name": "EtiamVelAugue.avi",
                    "patch_description": "solution-oriented",
                    "patch_status_image": "--",
                    "vendor_name": "Gigabox",
                    "failed": "628",
                    "status_label": "--",
                    "patch_released_time": "1710916964000",
                    "patch_size": "88322",
                },
                {
                    "updated_time": "1699504705000",
                    "installed": "28",
                    "patch_status_label": "--",
                    "bulletin_id": "MSWU\\\\-7307",
                    "patch_noreboot": "1",
                    "update_name": "enoxaparin sodium",
                    "platform": "1",
                    "platform_name": "Windows",
                    "missing": "3",
                    "download_status": "--",
                    "first_name": "Hoffman's sloth",
                    "severity": "3",
                    "patch_id": "619340",
                    "patch_name": "EtiamJusto.tiff",
                    "patch_description": "content-based",
                    "patch_status_image": "--",
                    "vendor_name": "Ntag",
                    "failed": "313",
                    "status_label": "--",
                    "patch_released_time": "1711304035000",
                    "patch_size": "540618375",
                },
                {
                    "updated_time": "1716451233000",
                    "installed": "977",
                    "patch_status_label": "--",
                    "bulletin_id": "TU\\\\-5821",
                    "patch_noreboot": "1",
                    "update_name": "Potassium Phosphate, Monobasic and Potassium Phosphate, Dibasic",
                    "platform": "1",
                    "platform_name": "Windows",
                    "missing": "5",
                    "download_status": "--",
                    "first_name": "White-eye, pale",
                    "severity": "2",
                    "patch_id": "557640",
                    "patch_name": "NamTristique.ppt",
                    "patch_description": "complexity",
                    "patch_status_image": "--",
                    "vendor_name": "Vinder",
                    "failed": "06",
                    "status_label": "--",
                    "patch_released_time": "1710536812000",
                    "patch_size": "1913854",
                },
                {
                    "updated_time": "1715434681000",
                    "installed": "15",
                    "patch_status_label": "--",
                    "bulletin_id": "MSWU\\\\-5980",
                    "patch_noreboot": "1",
                    "update_name": "BENZALKONIUM CHLORIDE",
                    "platform": "1",
                    "platform_name": "Windows",
                    "missing": "6",
                    "download_status": "--",
                    "first_name": "Porcupine, crested",
                    "severity": "3",
                    "patch_id": "790982",
                    "patch_name": "LeoOdioPorttitor.jpeg",
                    "patch_description": "Programmable",
                    "patch_status_image": "--",
                    "vendor_name": "Quire",
                    "failed": "632",
                    "status_label": "--",
                    "patch_released_time": "1727092790000",
                    "patch_size": "50049031",
                },
                {
                    "updated_time": "1724156458000",
                    "installed": "274",
                    "patch_status_label": "--",
                    "bulletin_id": "TU\\\\-7427",
                    "patch_noreboot": "1",
                    "update_name": "OCTINOXATE, OCTISALATE, OCTOCRYLENE, AVOBENZONE",
                    "platform": "1",
                    "platform_name": "Windows",
                    "missing": "58",
                    "download_status": "--",
                    "first_name": "Eagle, white-bellied sea",
                    "severity": "0",
                    "patch_id": "623090",
                    "patch_name": "MaurisSit.tiff",
                    "patch_description": "adapter",
                    "patch_status_image": "--",
                    "vendor_name": "Feedfire",
                    "failed": "24",
                    "status_label": "--",
                    "patch_released_time": "1696888035000",
                    "patch_size": "289618",
                },
                {
                    "updated_time": "1699125130000",
                    "installed": "3",
                    "patch_status_label": "--",
                    "bulletin_id": "TU\\\\-5695",
                    "patch_noreboot": "0",
                    "update_name": "OCTINOXATE and TITANIUM DIOXIDE",
                    "platform": "1",
                    "platform_name": "Windows",
                    "missing": "64",
                    "download_status": "--",
                    "first_name": "Common goldeneye",
                    "severity": "2",
                    "patch_id": "113852",
                    "patch_name": "MolestieHendrerit.ppt",
                    "patch_description": "algorithm",
                    "patch_status_image": "--",
                    "vendor_name": "Cogibox",
                    "failed": "777",
                    "status_label": "--",
                    "patch_released_time": "1702030937000",
                    "patch_size": "1162",
                },
                {
                    "updated_time": "1714779519000",
                    "installed": "932",
                    "patch_status_label": "--",
                    "bulletin_id": "MSWU\\\\-8439",
                    "patch_noreboot": "0",
                    "update_name": "ethyl alcohol",
                    "platform": "1",
                    "platform_name": "Windows",
                    "missing": "37",
                    "download_status": "--",
                    "first_name": "Jackal, indian",
                    "severity": "1",
                    "patch_id": "552230",
                    "patch_name": "PraesentLectus.ppt",
                    "patch_description": "Virtual",
                    "patch_status_image": "--",
                    "vendor_name": "Skippad",
                    "failed": "45",
                    "status_label": "--",
                    "patch_released_time": "1697560850000",
                    "patch_size": "5251528",
                },
                {
                    "updated_time": "1721330343000",
                    "installed": "58",
                    "patch_status_label": "--",
                    "bulletin_id": "TU\\\\-7233",
                    "patch_noreboot": "0",
                    "update_name": "chlorpheniramine maleate, ibuprofen, and phenylephrine hydrochloride",
                    "platform": "1",
                    "platform_name": "Windows",
                    "missing": "5",
                    "download_status": "--",
                    "first_name": "White-winged tern",
                    "severity": "3",
                    "patch_id": "176164",
                    "patch_name": "Massa.tiff",
                    "patch_description": "moderator",
                    "patch_status_image": "--",
                    "vendor_name": "Ailane",
                    "failed": "5",
                    "status_label": "--",
                    "patch_released_time": "1717079600000",
                    "patch_size": "611432",
                },
                {
                    "updated_time": "1707489693000",
                    "installed": "492",
                    "patch_status_label": "--",
                    "bulletin_id": "MSWU\\\\-6849",
                    "patch_noreboot": "0",
                    "update_name": "Avobenzone, Octisalate and Octocrylene",
                    "platform": "1",
                    "platform_name": "Windows",
                    "missing": "96",
                    "download_status": "--",
                    "first_name": "Asian elephant",
                    "severity": "2",
                    "patch_id": "246854",
                    "patch_name": "Mauris.avi",
                    "patch_description": "Vision-oriented",
                    "patch_status_image": "--",
                    "vendor_name": "Realcube",
                    "failed": "675",
                    "status_label": "--",
                    "patch_released_time": "1705860998000",
                    "patch_size": "538635204",
                },
                {
                    "updated_time": "1700712136000",
                    "installed": "88",
                    "patch_status_label": "--",
                    "bulletin_id": "MSWU\\\\-0079",
                    "patch_noreboot": "1",
                    "update_name": "ruxolitinib",
                    "platform": "1",
                    "platform_name": "Windows",
                    "missing": "83",
                    "download_status": "--",
                    "first_name": "Weaver, chestnut",
                    "severity": "2",
                    "patch_id": "490180",
                    "patch_name": "PlateaDictumst.ppt",
                    "patch_description": "info-mediaries",
                    "patch_status_image": "--",
                    "vendor_name": "Jabbercube",
                    "failed": "2",
                    "status_label": "--",
                    "patch_released_time": "1710701297000",
                    "patch_size": "099800144",
                },
                {
                    "updated_time": "1724053887000",
                    "installed": "1",
                    "patch_status_label": "--",
                    "bulletin_id": "MSWU\\\\-8219",
                    "patch_noreboot": "1",
                    "update_name": "Octinoxate and Oxybenzone",
                    "platform": "1",
                    "platform_name": "Windows",
                    "missing": "117",
                    "download_status": "--",
                    "first_name": "American black bear",
                    "severity": "0",
                    "patch_id": "530670",
                    "patch_name": "LobortisVelDapibus.xls",
                    "patch_description": "Enterprise-wide",
                    "patch_status_image": "--",
                    "vendor_name": "Browsecat",
                    "failed": "2",
                    "status_label": "--",
                    "patch_released_time": "1704720945000",
                    "patch_size": "356406081",
                },
                {
                    "updated_time": "1706999247000",
                    "installed": "5",
                    "patch_status_label": "--",
                    "bulletin_id": "MSWU\\\\-9682",
                    "patch_noreboot": "0",
                    "update_name": "Acetaminophen, Dextromethorphan HBr, Guaifenesin, Phenylephrine HCl",
                    "platform": "1",
                    "platform_name": "Windows",
                    "missing": "65",
                    "download_status": "--",
                    "first_name": "Agama lizard (unidentified)",
                    "severity": "2",
                    "patch_id": "002551",
                    "patch_name": "Iaculis.pdf",
                    "patch_description": "open system",
                    "patch_status_image": "--",
                    "vendor_name": "Yakijo",
                    "failed": "89",
                    "status_label": "--",
                    "patch_released_time": "1700476244000",
                    "patch_size": "22800",
                },
                {
                    "updated_time": "1704374290000",
                    "installed": "9",
                    "patch_status_label": "--",
                    "bulletin_id": "TU\\\\-1725",
                    "patch_noreboot": "0",
                    "update_name": "Naproxen",
                    "platform": "1",
                    "platform_name": "Windows",
                    "missing": "7",
                    "download_status": "--",
                    "first_name": "Common nighthawk",
                    "severity": "1",
                    "patch_id": "030863",
                    "patch_name": "Lacinia.tiff",
                    "patch_description": "Multi-channelled",
                    "patch_status_image": "--",
                    "vendor_name": "Youspan",
                    "failed": "049",
                    "status_label": "--",
                    "patch_released_time": "1709365989000",
                    "patch_size": "77068",
                },
                {
                    "updated_time": "1720027913000",
                    "installed": "66",
                    "patch_status_label": "--",
                    "bulletin_id": "MSWU\\\\-0483",
                    "patch_noreboot": "1",
                    "update_name": "Pyrithione Zinc",
                    "platform": "1",
                    "platform_name": "Windows",
                    "missing": "15",
                    "download_status": "--",
                    "first_name": "Dove, emerald-spotted wood",
                    "severity": "2",
                    "patch_id": "269072",
                    "patch_name": "Ligula.xls",
                    "patch_description": "motivating",
                    "patch_status_image": "--",
                    "vendor_name": "Innojam",
                    "failed": "9",
                    "status_label": "--",
                    "patch_released_time": "1707763384000",
                    "patch_size": "321625995",
                },
                {
                    "updated_time": "1725601166000",
                    "installed": "098",
                    "patch_status_label": "--",
                    "bulletin_id": "MSWU\\\\-6451",
                    "patch_noreboot": "0",
                    "update_name": "Titanium Dioxide",
                    "platform": "1",
                    "platform_name": "Windows",
                    "missing": "9",
                    "download_status": "--",
                    "first_name": "Marmot, hoary",
                    "severity": "1",
                    "patch_id": "433801",
                    "patch_name": "Eget.jpeg",
                    "patch_description": "Polarised",
                    "patch_status_image": "--",
                    "vendor_name": "Quimm",
                    "failed": "299",
                    "status_label": "--",
                    "patch_released_time": "1721355374000",
                    "patch_size": "8458289",
                },
                {
                    "updated_time": "1701668706000",
                    "installed": "9",
                    "patch_status_label": "--",
                    "bulletin_id": "MSWU\\\\-2270",
                    "patch_noreboot": "1",
                    "update_name": "Benzocaine 20%, Menthol, Benzalkonium Chloride",
                    "platform": "1",
                    "platform_name": "Windows",
                    "missing": "432",
                    "download_status": "--",
                    "first_name": "Capuchin, white-fronted",
                    "severity": "3",
                    "patch_id": "243481",
                    "patch_name": "MagnisDis.jpeg",
                    "patch_description": "Pre-emptive",
                    "patch_status_image": "--",
                    "vendor_name": "Gigashots",
                    "failed": "367",
                    "status_label": "--",
                    "patch_released_time": "1710247644000",
                    "patch_size": "239758",
                },
                {
                    "updated_time": "1727479107000",
                    "installed": "597",
                    "patch_status_label": "--",
                    "bulletin_id": "MSWU\\\\-1874",
                    "patch_noreboot": "1",
                    "update_name": "Haloperidol",
                    "platform": "1",
                    "platform_name": "Windows",
                    "missing": "32",
                    "download_status": "--",
                    "first_name": "Gambel's quail",
                    "severity": "0",
                    "patch_id": "432502",
                    "patch_name": "PosuereMetus.ppt",
                    "patch_description": "intermediate",
                    "patch_status_image": "--",
                    "vendor_name": "Topicshots",
                    "failed": "426",
                    "status_label": "--",
                    "patch_released_time": "1726992614000",
                    "patch_size": "24707",
                },
                {
                    "updated_time": "1720755471000",
                    "installed": "9",
                    "patch_status_label": "--",
                    "bulletin_id": "MSWU\\\\-6211",
                    "patch_noreboot": "1",
                    "update_name": "Amlodipine Besylate",
                    "platform": "1",
                    "platform_name": "Windows",
                    "missing": "24",
                    "download_status": "--",
                    "first_name": "Giant anteater",
                    "severity": "0",
                    "patch_id": "680995",
                    "patch_name": "LectusInEst.ppt",
                    "patch_description": "success",
                    "patch_status_image": "--",
                    "vendor_name": "Minyx",
                    "failed": "25",
                    "status_label": "--",
                    "patch_released_time": "1715991358000",
                    "patch_size": "93639750",
                },
                {
                    "updated_time": "1721145830000",
                    "installed": "115",
                    "patch_status_label": "--",
                    "bulletin_id": "TU\\\\-4514",
                    "patch_noreboot": "1",
                    "update_name": "Ethyl Alcohol",
                    "platform": "1",
                    "platform_name": "Windows",
                    "missing": "2",
                    "download_status": "--",
                    "first_name": "Agile wallaby",
                    "severity": "3",
                    "patch_id": "259088",
                    "patch_name": "CondimentumCurabitur.txt",
                    "patch_description": "help-desk",
                    "patch_status_image": "--",
                    "vendor_name": "Skipfire",
                    "failed": "5",
                    "status_label": "--",
                    "patch_released_time": "1725626370000",
                    "patch_size": "373739",
                },
                {
                    "updated_time": "1715018325000",
                    "installed": "1",
                    "patch_status_label": "--",
                    "bulletin_id": "MSWU\\\\-1326",
                    "patch_noreboot": "0",
                    "update_name": "Octinoxate, Oxybenzone, Titanium Dioxide",
                    "platform": "1",
                    "platform_name": "Windows",
                    "missing": "04",
                    "download_status": "--",
                    "first_name": "Curlew, black",
                    "severity": "3",
                    "patch_id": "555918",
                    "patch_name": "SedInterdumVenenatis.avi",
                    "patch_description": "Graphic Interface",
                    "patch_status_image": "--",
                    "vendor_name": "Yadel",
                    "failed": "14",
                    "status_label": "--",
                    "patch_released_time": "1726482279000",
                    "patch_size": "7393",
                },
            ],
            "limit": 25,
            "page": 1,
        },
        "message_version": "1.4",
        "status": "success",
    },
]
