__MOCK_ALLSYSTEMS_RESPONSES = [
    {
        "message_type": "allsystems",
        "message_response": {
            "total": 30,
            "allsystems": [
                {
                    "total_driver_patches": 10,
                    "resource_health_status": 0,
                    "missing_bios_patches": 94,
                    "resource_id": 500337625,
                    "os_name": "Windows 10",
                    "service_pack": "Windows 10 Version 22H2 x64",
                    "os_platform_name": "Windows",
                    "resourcetorebootdetails.reboot_req_status": True,
                    "resource_health_status": 1,
                },
                {
                    "total_driver_patches": 29,
                    "resource_health_status": 3,
                    "missing_bios_patches": 75,
                    "resource_id": 721887886,
                    "os_name": "Windows 10",
                    "service_pack": "Windows 10 Version 22H2 x64",
                    "os_platform_name": "Windows",
                    "resourcetorebootdetails.reboot_req_status": True,
                    "resource_health_status": 1,
                },
                {
                    "total_driver_patches": 32,
                    "resource_health_status": 0,
                    "missing_bios_patches": 14,
                    "resource_id": 384743747,
                    "os_name": "Windows 10",
                    "service_pack": "Windows 10 Version 22H2 x64",
                    "os_platform_name": "Windows",
                    "resourcetorebootdetails.reboot_req_status": True,
                    "resource_health_status": 1,
                },
                {
                    "total_driver_patches": 1,
                    "resource_health_status": 3,
                    "missing_bios_patches": 54,
                    "resource_id": 204251801,
                    "os_name": "Windows 10",
                    "service_pack": "Windows 10 Version 22H2 x64",
                    "os_platform_name": "Windows",
                    "resourcetorebootdetails.reboot_req_status": True,
                    "resource_health_status": 1,
                },
                {
                    "total_driver_patches": 2,
                    "resource_health_status": 2,
                    "missing_bios_patches": 37,
                    "resource_id": 676462385,
                    "os_name": "Windows 10",
                    "service_pack": "Windows 10 Version 22H2 x64",
                    "os_platform_name": "Windows",
                    "resourcetorebootdetails.reboot_req_status": True,
                    "resource_health_status": 1,
                },
                {
                    "total_driver_patches": 81,
                    "resource_health_status": 3,
                    "missing_bios_patches": 39,
                    "resource_id": 395619157,
                    "os_name": "Windows 10",
                    "service_pack": "Windows 10 Version 22H2 x64",
                    "os_platform_name": "Windows",
                    "resourcetorebootdetails.reboot_req_status": True,
                    "resource_health_status": 1,
                },
                {
                    "total_driver_patches": 45,
                    "resource_health_status": 3,
                    "missing_bios_patches": 9,
                    "resource_id": 638682209,
                    "os_name": "Windows 10",
                    "service_pack": "Windows 10 Version 22H2 x64",
                    "os_platform_name": "Windows",
                    "resourcetorebootdetails.reboot_req_status": True,
                    "resource_health_status": 1,
                },
                {
                    "total_driver_patches": 11,
                    "resource_health_status": 2,
                    "missing_bios_patches": 98,
                    "resource_id": 644590007,
                    "os_name": "Windows 10",
                    "service_pack": "Windows 10 Version 22H2 x64",
                    "os_platform_name": "Windows",
                    "resourcetorebootdetails.reboot_req_status": True,
                    "resource_health_status": 1,
                },
                {
                    "total_driver_patches": 96,
                    "resource_health_status": 2,
                    "missing_bios_patches": 83,
                    "resource_id": 458641551,
                    "os_name": "Windows 10",
                    "service_pack": "Windows 10 Version 22H2 x64",
                    "os_platform_name": "Windows",
                    "resourcetorebootdetails.reboot_req_status": True,
                    "resource_health_status": 1,
                },
                {
                    "total_driver_patches": 43,
                    "resource_health_status": 1,
                    "missing_bios_patches": 67,
                    "resource_id": 955176011,
                    "os_name": "Windows 10",
                    "service_pack": "Windows 10 Version 22H2 x64",
                    "os_platform_name": "Windows",
                    "resourcetorebootdetails.reboot_req_status": True,
                    "resource_health_status": 1,
                },
                {
                    "total_driver_patches": 99,
                    "resource_health_status": 3,
                    "missing_bios_patches": 5,
                    "resource_id": 613257311,
                    "os_name": "Windows 10",
                    "service_pack": "Windows 10 Version 22H2 x64",
                    "os_platform_name": "Windows",
                    "resourcetorebootdetails.reboot_req_status": True,
                    "resource_health_status": 1,
                },
                {
                    "total_driver_patches": 21,
                    "resource_health_status": 1,
                    "missing_bios_patches": 3,
                    "resource_id": 373144968,
                    "os_name": "Windows 10",
                    "service_pack": "Windows 10 Version 22H2 x64",
                    "os_platform_name": "Windows",
                    "resourcetorebootdetails.reboot_req_status": True,
                    "resource_health_status": 1,
                },
                {
                    "total_driver_patches": 64,
                    "resource_health_status": 3,
                    "missing_bios_patches": 83,
                    "resource_id": 204715226,
                    "os_name": "Windows 10",
                    "service_pack": "Windows 10 Version 22H2 x64",
                    "os_platform_name": "Windows",
                    "resourcetorebootdetails.reboot_req_status": True,
                    "resource_health_status": 1,
                },
                {
                    "total_driver_patches": 40,
                    "resource_health_status": 0,
                    "missing_bios_patches": 68,
                    "resource_id": 365465236,
                    "os_name": "Windows 10",
                    "service_pack": "Windows 10 Version 22H2 x64",
                    "os_platform_name": "Windows",
                    "resourcetorebootdetails.reboot_req_status": True,
                    "resource_health_status": 1,
                },
                {
                    "total_driver_patches": 28,
                    "resource_health_status": 1,
                    "missing_bios_patches": 83,
                    "resource_id": 473976421,
                    "os_name": "Windows 10",
                    "service_pack": "Windows 10 Version 22H2 x64",
                    "os_platform_name": "Windows",
                    "resourcetorebootdetails.reboot_req_status": True,
                    "resource_health_status": 1,
                },
                {
                    "total_driver_patches": 85,
                    "resource_health_status": 2,
                    "missing_bios_patches": 50,
                    "resource_id": 222488806,
                    "os_name": "Windows 10",
                    "service_pack": "Windows 10 Version 22H2 x64",
                    "os_platform_name": "Windows",
                    "resourcetorebootdetails.reboot_req_status": True,
                    "resource_health_status": 1,
                },
                {
                    "total_driver_patches": 56,
                    "resource_health_status": 0,
                    "missing_bios_patches": 2,
                    "resource_id": 269101443,
                    "os_name": "Windows 10",
                    "service_pack": "Windows 10 Version 22H2 x64",
                    "os_platform_name": "Windows",
                    "resourcetorebootdetails.reboot_req_status": True,
                    "resource_health_status": 1,
                },
                {
                    "total_driver_patches": 67,
                    "resource_health_status": 1,
                    "missing_bios_patches": 53,
                    "resource_id": 683169854,
                    "os_name": "Windows 10",
                    "service_pack": "Windows 10 Version 22H2 x64",
                    "os_platform_name": "Windows",
                    "resourcetorebootdetails.reboot_req_status": True,
                    "resource_health_status": 1,
                },
                {
                    "total_driver_patches": 25,
                    "resource_health_status": 0,
                    "missing_bios_patches": 50,
                    "resource_id": 352941570,
                    "os_name": "Windows 10",
                    "service_pack": "Windows 10 Version 22H2 x64",
                    "os_platform_name": "Windows",
                    "resourcetorebootdetails.reboot_req_status": True,
                    "resource_health_status": 1,
                },
                {
                    "total_driver_patches": 82,
                    "resource_health_status": 0,
                    "missing_bios_patches": 85,
                    "resource_id": 135498558,
                    "os_name": "Windows 10",
                    "service_pack": "Windows 10 Version 22H2 x64",
                    "os_platform_name": "Windows",
                    "resourcetorebootdetails.reboot_req_status": True,
                    "resource_health_status": 1,
                },
                {
                    "total_driver_patches": 37,
                    "resource_health_status": 3,
                    "missing_bios_patches": 13,
                    "resource_id": 190133918,
                    "os_name": "Windows 10",
                    "service_pack": "Windows 10 Version 22H2 x64",
                    "os_platform_name": "Windows",
                    "resourcetorebootdetails.reboot_req_status": True,
                    "resource_health_status": 1,
                },
                {
                    "total_driver_patches": 70,
                    "resource_health_status": 2,
                    "missing_bios_patches": 19,
                    "resource_id": 643265042,
                    "os_name": "Windows 10",
                    "service_pack": "Windows 10 Version 22H2 x64",
                    "os_platform_name": "Windows",
                    "resourcetorebootdetails.reboot_req_status": True,
                    "resource_health_status": 1,
                },
                {
                    "total_driver_patches": 31,
                    "resource_health_status": 1,
                    "missing_bios_patches": 60,
                    "resource_id": 447894760,
                    "os_name": "Windows 10",
                    "service_pack": "Windows 10 Version 22H2 x64",
                    "os_platform_name": "Windows",
                    "resourcetorebootdetails.reboot_req_status": True,
                    "resource_health_status": 1,
                },
                {
                    "total_driver_patches": 94,
                    "resource_health_status": 2,
                    "missing_bios_patches": 28,
                    "resource_id": 440622232,
                    "os_name": "Windows 10",
                    "service_pack": "Windows 10 Version 22H2 x64",
                    "os_platform_name": "Windows",
                    "resourcetorebootdetails.reboot_req_status": "--",
                    "resource_health_status": 1,
                },
                {
                    "total_driver_patches": 58,
                    "resource_health_status": 1,
                    "missing_bios_patches": 80,
                    "resource_id": 253108650,
                    "os_name": "Windows 10",
                    "service_pack": "Windows 10 Version 22H2 x64",
                    "os_platform_name": "Windows",
                    "resourcetorebootdetails.reboot_req_status": "--",
                    "resource_health_status": 1,
                },
            ],
            "limit": 25,
            "page": 1,
        },
        "message_version": "1.4",
        "status": "success",
    },
    {
        "message_type": "allsystems",
        "message_response": {
            "total": 30,
            "allsystems": [
                {
                    "total_driver_patches": 74,
                    "resource_health_status": 2,
                    "missing_bios_patches": 66,
                    "resource_id": 936878743,
                    "os_name": "Windows 10",
                    "service_pack": "Windows 10 Version 22H2 x64",
                    "os_platform_name": "Windows",
                    "resourcetorebootdetails.reboot_req_status": False,
                    "resource_health_status": 2,
                },
                {
                    "total_driver_patches": 52,
                    "resource_health_status": 0,
                    "missing_bios_patches": 51,
                    "resource_id": 139655031,
                    "os_name": "Windows 10",
                    "service_pack": "Windows 10 Version 22H2 x64",
                    "os_platform_name": "Windows",
                    "resourcetorebootdetails.reboot_req_status": True,
                    "resource_health_status": 3,
                },
                {
                    "total_driver_patches": 90,
                    "resource_health_status": 0,
                    "missing_bios_patches": 43,
                    "resource_id": 230235032,
                    "os_name": "Windows 10",
                    "service_pack": "Windows 10 Version 22H2 x64",
                    "os_platform_name": "Windows",
                    "resourcetorebootdetails.reboot_req_status": True,
                    "resource_health_status": 1,
                },
                {
                    "total_driver_patches": 46,
                    "resource_health_status": 1,
                    "missing_bios_patches": 99,
                    "resource_id": 696214992,
                    "os_name": "Windows 10",
                    "service_pack": "Windows 10 Version 22H2 x64",
                    "os_platform_name": "Windows",
                    "resourcetorebootdetails.reboot_req_status": True,
                    "resource_health_status": 3,
                },
                {
                    "total_driver_patches": 45,
                    "resource_health_status": 1,
                    "missing_bios_patches": 92,
                    "resource_id": 502350449,
                    "os_name": "Windows 10",
                    "service_pack": "Windows 10 Version 22H2 x64",
                    "os_platform_name": "Windows",
                    "resourcetorebootdetails.reboot_req_status": True,
                    "resource_health_status": "--",
                },
            ],
            "limit": 25,
            "page": 2,
        },
        "message_version": "1.4",
        "status": "success",
    },
]
