acr_score: true
agent_names: true
agent_names_0: true
agent_uuid: true
aws_availability_zone: true
aws_ec2_instance_ami_id: true
aws_ec2_instance_group_name: true
aws_ec2_instance_id: true
aws_ec2_instance_state_name: true
aws_ec2_instance_type: true
aws_ec2_name: true
aws_ec2_product_code: true
aws_owner_id: true
aws_region: true
aws_subnet_id: true
aws_vpc_id: true
azure_resource_id: true
azure_vm_id: true
bigfix_asset_id: true
bios_uuid: true
created_at: true
deleted_at: true
deleted_by: true
exposure_score: true
first_scan_time: true
first_seen: true
fqdns: true
fqdns_0: true
fqdns_1: true
gcp_instance_id: true
gcp_project_id: true
gcp_zone: true
has_agent: true
has_plugin_results: true
hostnames: true
hostnames_0: true
id: true
installed_software: false
ipv4s_0: true
ipv4s_1: true
ipv4s_2: true
ipv4s_3: true
ipv4s_4: true
ipv4s_5: true
ipv4s_6: true
ipv4s_7: true
ipv6s: true
ipv6s_0: true
ipv6s_1: true
ipv6s_2: true
ipv6s_3: true
last_authenticated_scan_date: true
last_licensed_scan_date: true
last_scan_id: true
last_scan_time: true
last_schedule_id: true
last_seen: true
mac_addresses: true
mac_addresses_0: true
manufacturer_tpm_ids: true
mcafee_epo_agent_guid: true
mcafee_epo_guid: true
netbios_names: true
netbios_names_0: true
network_id: true
network_interfaces: false
network_name: true
open_ports: true
operating_systems: true
operating_systems_0: true
operating_systems_1: true
operating_systems_2: true
operating_systems_3: true
qualys_asset_ids: true
qualys_host_ids: true
servicenow_sysid: true
sources: true
sources_0_first_seen: true
sources_0_last_seen: true
sources_0_name: true
sources_1_first_seen: true
sources_1_last_seen: true
sources_1_name: true
sources_2_first_seen: true
sources_2_last_seen: true
sources_2_name: true
ssh_fingerprints: true
ssh_fingerprints_0: true
symantec_ep_hardware_keys: true
system_types: true
system_types_0: true
tags_0_added_at: true
tags_0_added_by: true
tags_0_key: true
tags_0_uuid: true
tags_0_value: true
tags_1_added_at: true
tags_1_added_by: true
tags_1_key: true
tags_1_uuid: true
tags_1_value: true
tags_2_added_at: true
tags_2_added_by: true
tags_2_key: true
tags_2_uuid: true
tags_2_value: true
tags_3_added_at: true
tags_3_added_by: true
tags_3_key: true
tags_3_uuid: true
tags_3_value: true
tags_4_added_at: true
tags_4_added_by: true
tags_4_key: true
tags_4_uuid: true
tags_4_value: true
tags_5_added_at: true
tags_5_added_by: true
tags_5_key: true
tags_5_uuid: true
tags_5_value: true
tags_6_added_at: true
tags_6_added_by: true
tags_6_key: true
tags_6_uuid: true
tags_6_value: true
tags_7_added_at: true
tags_7_added_by: true
tags_7_key: true
tags_7_uuid: true
tags_7_value: true
tags_8_added_at: true
tags_8_added_by: true
tags_8_key: true
tags_8_uuid: true
tags_8_value: true
tags_9_added_at: true
tags_9_added_by: true
tags_9_key: true
tags_9_uuid: true
tags_9_value: true
terminated_at: true
terminated_by: true
updated_at: true
