asset_agent_uuid: true
asset_bios_uuid: true
asset_device_type: true
asset_fqdn: true
asset_hostname: true
asset_ipv4: true
asset_ipv6: true
asset_last_authenticated_results: true
asset_mac_address: true
asset_netbios_name: true
asset_network_id: true
asset_operating_system_0: true
asset_operating_system_1: true
asset_operating_system_2: true
asset_operating_system_3: true
asset_tracked: true
asset_uuid: true
first_found: true
indexed: true
last_fixed: true
last_found: true
output: false
plugin_bid_0: true
plugin_canvas_package: true
plugin_checks_for_default_account: true
plugin_checks_for_malware: true
plugin_cpe: false
plugin_cvss3_base_score: true
plugin_cvss3_temporal_score: true
plugin_cvss3_temporal_vector: true
plugin_cvss3_temporal_vector_exploitability: true
plugin_cvss3_temporal_vector_raw: true
plugin_cvss3_temporal_vector_remediation_level: true
plugin_cvss3_temporal_vector_report_confidence: true
plugin_cvss3_vector_access_complexity: true
plugin_cvss3_vector_access_vector: true
plugin_cvss3_vector_availability_impact: true
plugin_cvss3_vector_confidentiality_impact: true
plugin_cvss3_vector_integrity_impact: true
plugin_cvss3_vector_raw: true
plugin_cvss_base_score: true
plugin_cvss_temporal_score: true
plugin_cvss_temporal_vector: true
plugin_cvss_temporal_vector_exploitability: true
plugin_cvss_temporal_vector_raw: true
plugin_cvss_temporal_vector_remediation_level: true
plugin_cvss_temporal_vector_report_confidence: true
plugin_cvss_vector_access_complexity: true
plugin_cvss_vector_access_vector: true
plugin_cvss_vector_authentication: true
plugin_cvss_vector_availability_impact: true
plugin_cvss_vector_confidentiality_impact: true
plugin_cvss_vector_integrity_impact: true
plugin_cvss_vector_raw: true
plugin_d2_elliot_name: true
plugin_description: false
plugin_exploit_available: true
plugin_exploit_framework_canvas: true
plugin_exploit_framework_core: true
plugin_exploit_framework_d2_elliot: true
plugin_exploit_framework_exploithub: true
plugin_exploit_framework_metasploit: true
plugin_exploitability_ease: true
plugin_exploited_by_malware: true
plugin_exploited_by_nessus: true
plugin_family: true
plugin_family_id: true
plugin_has_patch: true
plugin_id: true
plugin_in_the_news: true
plugin_metasploit_name: true
plugin_modification_date: true
plugin_ms_bulletin_0: false
plugin_ms_bulletin_1: false
plugin_ms_bulletin_10: false
plugin_ms_bulletin_11: false
plugin_ms_bulletin_12: false
plugin_ms_bulletin_13: false
plugin_ms_bulletin_14: false
plugin_ms_bulletin_15: false
plugin_ms_bulletin_16: false
plugin_ms_bulletin_17: false
plugin_ms_bulletin_18: false
plugin_ms_bulletin_19: false
plugin_ms_bulletin_2: false
plugin_ms_bulletin_20: false
plugin_ms_bulletin_21: false
plugin_ms_bulletin_22: false
plugin_ms_bulletin_23: false
plugin_ms_bulletin_24: false
plugin_ms_bulletin_25: false
plugin_ms_bulletin_26: false
plugin_ms_bulletin_27: false
plugin_ms_bulletin_28: false
plugin_ms_bulletin_29: false
plugin_ms_bulletin_3: false
plugin_ms_bulletin_4: false
plugin_ms_bulletin_5: false
plugin_ms_bulletin_6: false
plugin_ms_bulletin_7: false
plugin_ms_bulletin_8: false
plugin_ms_bulletin_9: false
plugin_name: true
plugin_patch_publication_date: true
plugin_publication_date: true
plugin_risk_factor: true
plugin_see_also_0: false
plugin_see_also_1: false
plugin_see_also_10: false
plugin_see_also_11: false
plugin_see_also_12: false
plugin_see_also_13: false
plugin_see_also_14: false
plugin_see_also_15: false
plugin_see_also_16: false
plugin_see_also_17: false
plugin_see_also_18: false
plugin_see_also_19: false
plugin_see_also_2: false
plugin_see_also_20: false
plugin_see_also_21: false
plugin_see_also_22: false
plugin_see_also_23: false
plugin_see_also_24: false
plugin_see_also_25: false
plugin_see_also_26: false
plugin_see_also_27: false
plugin_see_also_28: false
plugin_see_also_29: false
plugin_see_also_3: false
plugin_see_also_30: false
plugin_see_also_31: false
plugin_see_also_32: false
plugin_see_also_33: false
plugin_see_also_34: false
plugin_see_also_35: false
plugin_see_also_4: false
plugin_see_also_5: false
plugin_see_also_6: false
plugin_see_also_7: false
plugin_see_also_8: false
plugin_see_also_9: false
plugin_solution: true
plugin_stig_severity: true
plugin_synopsis: true
plugin_type: true
plugin_unsupported_by_vendor: true
plugin_version: true
plugin_vpr_drivers_age_of_vuln_lower_bound: true
plugin_vpr_drivers_age_of_vuln_upper_bound: true
plugin_vpr_drivers_cvss3_impact_score: true
plugin_vpr_drivers_cvss_impact_score_predicted: true
plugin_vpr_drivers_exploit_code_maturity: true
plugin_vpr_drivers_product_coverage: true
plugin_vpr_drivers_threat_intensity_last28: true
plugin_vpr_drivers_threat_recency_lower_bound: true
plugin_vpr_drivers_threat_recency_upper_bound: true
plugin_vpr_drivers_threat_sources_last28_0: true
plugin_vpr_drivers_threat_sources_last28_1: true
plugin_vpr_score: true
plugin_vpr_updated: true
plugin_vuln_publication_date: true
plugin_xrefs: false
port_port: true
port_protocol: true
port_service: true
recast_reason: true
recast_rule_uuid: true
scan_schedule_uuid: true
scan_started_at: true
scan_uuid: true
severity: true
severity_default_id: true
severity_id: true
severity_modification_type: true
source: true
state: true
